apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: shop

namespace: shop-staging

resources:
- ../../base
- namespace.yaml
- hpa.yaml

patches:
  - path: patches/letsencrypt-staging.yaml
  - path: patches/hostname-staging.yaml
  - path: patches/resource-limit-cpu-ui.yaml
