prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: false
alertmanager: 
  enabled: true
  persistence:
    enabled: false
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: test-alertmanager-ce8-g1.sctp-sandbox.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "test-alertmanager-ce8-g1.sctp-sandbox.com"

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
      - job_name: node-exporter
        static_configs:
          - targets:
            - kube-prometheus-stack-prometheus-node-exporter.monitoring:9100
      - job_name: nginx
        static_configs:
          - targets:
            - ingress-nginx-controller-metrics.ingress-nginx:10254
server:
  persistentVolume:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - test-prom-ce8-g1.sctp-sandbox.com
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "test-prom-ce8-g1.sctp-sandbox.com"

