apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: ui
  namespace: shop-prod

spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui
  targetCPUUtilizationPercentage: 80