apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: shop

nameSuffix: -staging
namespace: shop-staging

resources:
- ../../base
- namespace.yaml

patches:
  - path: letsencrypt-staging.yaml
