apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest
  # Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes
  role: "${KARPENTER_NODE_ROLE_ARN}"
  # Optional, IAM instance profile to use for the node identity.
  # Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes
  # instanceProfile: "${KARPENTER_NODE_INSTANCE_PROFILE_NAME}"  
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME}
  securityGroupSelectorTerms:
    - tags:
        # karpenter.sh/discovery: ${CLUSTER_NAME}
        # aws:eks:cluster-name: ${CLUSTER_NAME}
        Name: ${CLUSTER_NAME}-node
  tags:
    app.kubernetes.io/created-by: eks-cluster-provisioner
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        type: karpenter
    spec:
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          # values: ["on-demand"]
          values: ["spot"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.medium"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: 6h
  limits:
    cpu: "10"
    memory: 20Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m