prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      external-dns.alpha.kubernetes.io/hostname: "admin-prom-ce8-g1.sctp-sandbox.com"
    hosts:
      - admin-prom-ce8-g1.sctp-sandbox.com
    paths:
      - /
    tls:
      - secretName: prometheus-general-tls
        hosts:
          - admin-prom-ce8-g1.sctp-sandbox.com
grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      external-dns.alpha.kubernetes.io/hostname: "admin-grafana-ce8-g1.sctp-sandbox.com"
    hosts:
      - admin-grafana-ce8-g1.sctp-sandbox.com
    tls:
      - secretName: grafana-general-tls
        hosts:
          - admin-grafana-ce8-g1.sctp-sandbox.com
prometheus-node-exporter:
  extraArgs:
    - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
    - --collector.systemd
    - --collector.ethtool
