apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: ui
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "shop-staging.sctp-sandbox.com"

spec:
  tls:
    - hosts:
        - "shop-staging.sctp-sandbox.com"
      secretName: shop-staging-tls # cert-manager will create this TLS secret
  rules:
    - host: "shop-staging.sctp-sandbox.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 80