name: Cleanup-tmp

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region"
        required: true
        default: "ap-southeast-1"

permissions:
  id-token: write       # Required for OIDC
  contents: read        # To read repo content

env:            
  OIDC_ROLE: arn:aws:iam::255945442255:role/github_oidc_role_ce8_capstone_G1
          
jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE }}
          aws-region: ${{ inputs.region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/eks-cluster

      - name: Export terraform outputs
        id: tfout
        run: |
          echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
        working-directory: ./terraform/eks-cluster

      # - name: Update kubeconfig
      #   run: aws eks update-kubeconfig --name ${{ steps.tfout.outputs.CLUSTER_NAME }}

      # - name: Uninstall all Helm releases
      #   run: |
      #     helm list -A -o json | jq -r '.[] | "\(.name) \(.namespace)"' | while read release ns
      #     do
      #       echo "Uninstalling Helm release: $release in namespace: $ns"
      #       helm uninstall "$release" -n "$ns" || true
      #     done

      # - name: Delete all remaining K8s resources
      #   run: |
      #     kubectl delete all --all -A || true

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform/eks-cluster
