name: Create and Bootstrap Cluster
run-name: Deploy shop (${{ github.event.inputs.retail-store }})

on:
  workflow_dispatch:
    inputs:
      retail-store:
        description: "Retail Store"
        type: choice
        options:
          - "staging"
          - "prod"
        default: "staging"
        required: true
      
      cloud-monitoring:
          description: "Grafana Cloud monitoring"
          type: boolean
          default: true
          required: true        

permissions:  
  id-token: write       # Required for OIDC
  contents: read        # To read repo content

env:
  region: "ap-southeast-1"

jobs:
  create-cluster:
    name: Create Cluster
    runs-on: ubuntu-latest
    outputs:
      cluster_name: ${{ steps.tfout.outputs.CLUSTER_NAME }}
      external_dns_role_arn: ${{ steps.tfout.outputs.EXTERNAL_DNS_ROLE_ARN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/eks-cluster

      - name: Terraform Plan
        working-directory: ./terraform/eks-cluster
        env:
          TF_VAR_region: ${{ env.region }}
        run: terraform plan
        
      - name: Terraform Apply
        working-directory: ./terraform/eks-cluster
        env:
          TF_VAR_region: ${{ env.region }}
        run: terraform apply -auto-approve

      - name: Export terraform outputs
        working-directory: ./terraform/eks-cluster
        id: tfout
        run: |
          echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
          echo "EXTERNAL_DNS_ROLE_ARN=$(terraform output -json external_dns_role_arn | jq -r '.[0]')" >> $GITHUB_OUTPUT

  metrics-server:
    name: Metrics Server
    runs-on: ubuntu-latest
    needs: [create-cluster]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}

      - name: Deploy Metrics Server
        working-directory: ./addons/metrics-server
        run: |
          chmod +x init.sh
          ./init.sh

  ingress:
    name: Ingress Controller
    runs-on: ubuntu-latest
    needs: [create-cluster]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}

      - name: Deploy Nginx Ingress Controller
        working-directory: ./addons/nginx-ingress
        run: |
          chmod +x init.sh
          ./init.sh

  external-dns:
    name: External DNS
    runs-on: ubuntu-latest
    needs: [create-cluster, ingress]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}

      - name: Deploy External DNS for Route53
        env:
          REGION: ${{ env.region }}
          EXTERNAL_DNS_ROLE_ARN: ${{ needs.create-cluster.outputs.external_dns_role_arn }}
        working-directory: ./addons/r53-externaldns
        run: |
          envsubst < values.yaml > values.tmp && mv values.tmp values.yaml
          chmod +x init.sh
          ./init.sh
  
  cert-manager:
    name: Cert Manager
    runs-on: ubuntu-latest
    needs: [create-cluster, ingress, external-dns]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}

      - name: Deploy Cert Manager
        env:
          EMAIL: ${{ secrets.EMAIL_ADDRESS }}
        working-directory: ./addons/cert-manager
        run: |
          chmod +x init.sh
          ./init.sh          
          envsubst < cluster-issuer-prod.yaml | kubectl apply -f -
          envsubst < cluster-issuer-staging.yaml | kubectl apply -f -
  
  shop:
    name: Shop
    runs-on: ubuntu-latest
    needs: [create-cluster, ingress, external-dns, cert-manager]
    if: ${{ github.event.inputs.retail-store == 'staging' || github.event.inputs.retail-store == 'prod' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}
          
      - name: Deploy Shop
        working-directory: ./apps/shop/overlays/${{ github.event.inputs.retail-store }}
        run: |
          kubectl apply -k .

  grafana-cloud:
    name: Grafana monitoring
    runs-on: ubuntu-latest
    needs: [create-cluster, ingress, external-dns, cert-manager]
    if: ${{ github.event.inputs.cloud-monitoring == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}

      - name: Deploy Grafana Cloud monitoring
        if: ${{ github.event.inputs.cloud-monitoring == 'true' }}
        env:
          GRAFANA_CLOUD_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_CLOUD_ACCESS_POLICY_TOKEN }}        
        working-directory: ./addons/grafana-cloud
        run: |
          envsubst < values.yaml > values.tmp && mv values.tmp values.yaml
          chmod +x init.sh
          ./init.sh        