name: Create and Bootstrap Cluster

on:
  workflow_dispatch:
    inputs:
      ingress-external-dns:
        description: "Ingress and External DNS"
        type: boolean
        default: true
        required: true

      retail-store:
        description: "Retail Store"
        type: choice
        options:
          - "v1"
          - "v2"
        default: "v2"
        required: true
      
      cloud-monitoring:
          description: "Grafana cloud monitoring"
          type: boolean
          default: false
          required: true

      karpenter:
          description: "AWS Karpenter autoscaler"
          type: boolean
          default: false
          required: true                   

      argocd:
        description: "ArgoCD"
        type: boolean
        default: false
        required: true

permissions:  
  id-token: write       # Required for OIDC
  contents: read        # To read repo content

env:
  region: "ap-southeast-1"

jobs:
  create-cluster:
    name: Create Cluster
    runs-on: ubuntu-latest
    timeout-minutes: 45 #change timeout to 45 minutes
    outputs:
      cluster_name: ${{ steps.tfout.outputs.CLUSTER_NAME }}
      cluster_endpoint: ${{ steps.tfout.outputs.CLUSTER_ENDPOINT }}
      external_dns_role_arn: ${{ steps.tfout.outputs.EXTERNAL_DNS_ROLE_ARN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/eks-cluster

      - name: Terraform Plan
        working-directory: ./terraform/eks-cluster
        env:
          TF_VAR_region: ${{ env.region }}
        run: terraform plan
        
      - name: Terraform Apply
        working-directory: ./terraform/eks-cluster
        env:
          TF_VAR_region: ${{ env.region }}
        run: terraform apply -auto-approve

      - name: Export terraform outputs
        working-directory: ./terraform/eks-cluster
        id: tfout
        run: |
          echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
          echo "CLUSTER_ENDPOINT=$(terraform output -raw cluster_endpoint)" >> $GITHUB_OUTPUT
          echo "EXTERNAL_DNS_ROLE_ARN=$(terraform output -json external_dns_role_arn | jq -r '.[0]')" >> $GITHUB_OUTPUT

  metrics-server:
    name: Metrics Server
    runs-on: ubuntu-latest
    needs: [create-cluster]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}

      - name: Deploy Metrics Server
        working-directory: ./addons/metrics-server
        run: |
          chmod +x init.sh
          ./init.sh

  ingress-external-dns:
    name: Ingress and External DNS
    runs-on: ubuntu-latest
    needs: [create-cluster]
    if: ${{ github.event.inputs.ingress-external-dns == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}

      - name: Deploy Nginx Ingress Controller
        if: ${{ github.event.inputs.ingress-external-dns }}
        working-directory: ./addons/nginx-ingress
        run: |
          chmod +x init.sh
          ./init.sh

      - name: Deploy External DNS for Route53
        if: ${{ github.event.inputs.ingress-external-dns }}
        env:
          REGION: ${{ env.region }}
          EXTERNAL_DNS_ROLE_ARN: ${{ needs.create-cluster.outputs.external_dns_role_arn }}
        working-directory: ./addons/r53-externaldns
        run: |
          envsubst < values.yaml > values.tmp && mv values.tmp values.yaml
          chmod +x init.sh
          ./init.sh
  
  cert-manager:
    name: Cert Manager
    runs-on: ubuntu-latest
    needs: [create-cluster, ingress-external-dns]
    if: ${{ github.event.inputs.ingress-external-dns == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}

      - name: Deploy Cert Manager
        env:
          EMAIL: ${{ secrets.EMAIL_ADDRESS }}
        working-directory: ./addons/cert-manager
        run: |
          chmod +x init.sh
          ./init.sh          
          envsubst < cluster-issuer-prod.yaml | kubectl apply -f -
          envsubst < cluster-issuer-staging.yaml | kubectl apply -f -

  online-retail-store:
    name: Online Retail Store
    runs-on: ubuntu-latest
    needs: [create-cluster, ingress-external-dns]
    if: ${{ github.event.inputs.retail-store == 'v1' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}
          
      - name: Deploy Online Retail Store
        working-directory: ./apps/shop
        run: |
          kubectl apply -k .
  
  online-retail-store-v2:
    name: Online Retail Store v2
    runs-on: ubuntu-latest
    needs: [create-cluster, ingress-external-dns]
    if: ${{ github.event.inputs.retail-store == 'v2' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}
          
      - name: Deploy Online Retail Store
        working-directory: ./apps/shop-v2/overlays/staging
        run: |
          kubectl apply -k .

  argocd:
    name: ArgoCD
    runs-on: ubuntu-latest
    needs: [create-cluster, ingress-external-dns]
    if: ${{ github.event.inputs.argocd == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}

      - name: Deploy ArgoCD
        if: ${{ github.event.inputs.argocd == 'true' }}
        working-directory: ./addons/argocd
        run: |
          chmod +x init.sh
          ./init.sh

  grafana-cloud:
    name: Grafana cloud monitoring
    runs-on: ubuntu-latest
    needs: [create-cluster, ingress-external-dns]
    if: ${{ github.event.inputs.cloud-monitoring == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}

      - name: Deploy Grafana cloud monitoring
        if: ${{ github.event.inputs.cloud-monitoring == 'true' }}
        env:
          GRAFANA_CLOUD_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_CLOUD_ACCESS_POLICY_TOKEN }}        
        working-directory: ./addons/grafana-cloud
        run: |
          envsubst < values.yaml > values.tmp && mv values.tmp values.yaml
          chmod +x init.sh
          ./init.sh
          
  karpenter:
    name: AWS Karpenter autoscaler
    runs-on: ubuntu-latest
    needs: [create-cluster]
    if: ${{ github.event.inputs.karpenter == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ env.region }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ needs.create-cluster.outputs.cluster_name }}

      - name: Deploy AWS Karpenter autoscaler
        if: ${{ github.event.inputs.karpenter == 'true' }}
        env:
          CLUSTER_NAME: ${{ needs.create-cluster.outputs.cluster_name }}
          CLUSTER_ENDPOINT: ${{ needs.create-cluster.outputs.cluster_endpoint }}        
        working-directory: ./addons/karpenter
        run: |
          echo "Karpenter autoscaler is not yet implemented"
          # envsubst < init.sh > init.tmp && mv init.tmp init.sh
          chmod +x init.sh
          ./init.sh