name: "Deploy Retail App"

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region"
        required: true
        default: "ap-southeast-1"

env:
  #EKS_REGION: "ap-southeast-1"
  #EKS_CLUSTER: "ce8-g1-capstone-cluster"
  OIDC_ROLE: ${{ secrets.OIDC_ROLE }}

permissions:
  id-token: write # Required for OIDC
  contents: read # To read repo content

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE }}
          aws-region: ${{ inputs.region }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check

          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

          kubectl version --client
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/eks-cluster
      
      - name: Export terraform outputs
        id: tfout
        run: |
          echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
        working-directory: ./terraform/eks-cluster
        
      - name: Connect to EKS cluster
        run: aws eks update-kubeconfig --name ${{ steps.tfout.outputs.CLUSTER_NAME }} --region ${{ inputs.region }}

        #  run: aws eks --region ${{ vars.EKS_REGION }} update-kubeconfig --name ${{ vars.EKS_CLUSTER }}

      # - name: Create namespace
      #   run: |
      #     kubectl create namespace shop
      - name: Deploy shop app
        run: |
          kubectl apply -k apps/shop

        # kubectl apply -f ./apps/shop/shop.yaml -n shop
        # kubectl apply -f ./apps/shop/ingress.yaml -n shop
