name: Load test
run-name: Load test (${{ github.event.inputs.environment }})

on:
  workflow_dispatch:
    inputs:
      duration:
        description: "Duration of the test"
        type: string
        default: 20s
        required: true
      users:
        description: "Number of virtual users"
        type: number
        default: 10
        required: true
      environment:
        description: "Environment to run load tests against"
        type: choice
        options:
          - staging
          - prod
        default: staging
        required: true
          
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: grafana/setup-k6-action@v1
        with:
          browser: true
      - uses: grafana/run-k6-action@v1
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
        with:
          cloud-run-locally: false
          flags: --verbose --vus ${{ github.event.inputs.users }} --duration $${{ github.event.inputs.duration }}
          path: |
            ./load-testing/k6/test-${{ github.event.inputs.environment }}.js
